### ISSUE TITLE
Check for executables pull problem

### ISSUE THREAD

**Issue by jacobrh91** [jacobrh91/Swift-T-Variant-Calling#25]
Hey @zo0z Azza, I think your latest push, Adding checks for executables and jars as per the runfile, broke the pipeline.

From what I saw, some functions passed in the config variables in something called 'var', when your additions expected them to be 'vars', or vice versa.

Can you try and fix this?

Thanks,
Jacob

**Comment by azzaea** [comment]
Ok... I'm looking at it now.

**Comment by jacobrh91** [comment]
Wow, you jumped on this quickly! What time is it there?

**Comment by azzaea** [comment]
It's almost 01:00 of Wednesday! I was up attempting to write a report, and then this came along, and honestly,  looking at code is just more fun! 

I think I found these places, so will be pushing in a few minutes.

**Comment by azzaea** [comment]
Kindly check the latest push, it should take care of this!

**Comment by jacobrh91** [comment]
Fix worked, closing issue
