### ISSUE TITLE
Timing.log in the deliverables folder is empty

### ISSUE THREAD

**Issue by jacobrh91** [jacobrh91/Swift-T-Variant-Calling#32]
Looking at the output of my 110 Node Blue Waters run, I noticed that the Timing.log has no data in it, just the header line.

**Comment by azzaea** [comment]
Currently, writing to the `Timing.log` happens only upon completion of a stage through the (logging function)[https://github.com/ncsa/Swift-T-Variant-Calling/blob/master/src/generalfunctions/general.swift#L58], and meanwhile, the intermediate data is stored as small files in the `TMP_SWIFT` directory. While it makes sense that partial results are still readily available, appending the Timing.log file concurrently would be unpredictable, so the approach of only writing to it upon stage completion was safer to implement.
I'm guessing that the run was not yet complete when you checked, or that there were an error and it didn't complete successfully.
